Feature api reg user
BuGalter/management-service pull request #1
Opened 2022-01-26 10:22 UTC by BuGalter

2022-01-27 08:52 UTC, rsarmurzinov requested changes

2022-01-27 08:52 UTC, rsarmurzinov commented on package.json
> +    "hapi-auth-jwt2": "^10.2.0",
у тебя есть готовое решение в starter-kit

2022-01-27 08:52 UTC, rsarmurzinov commented on src/server/api/user.ts
> +export async function userReg(r) {
нет проверки существует лт пользователь

2022-01-27 08:52 UTC, rsarmurzinov commented on src/server/api/user.ts
> +  if (user === null) {
if (!user)

2022-01-27 08:52 UTC, rsarmurzinov commented on src/server/api/user.ts
> +  const dataSession = { sessionId: newSession.id, userId: newSession.userId, };
лишняя переменная

2022-01-27 08:52 UTC, rsarmurzinov commented on src/server/config/config.ts
> +  token: {
в стартер ките уже готовый конфиг из него можно было скопировать

2022-01-28 14:38 UTC, BuGalter commented on package.json
> +    "hapi-auth-jwt2": "^10.2.0",
Исправил

2022-01-28 14:39 UTC, BuGalter commented on src/server/config/config.ts
> +  token: {
Исправил

2022-01-28 14:39 UTC, BuGalter commented on package.json
> +    "hapi-auth-jwt2": "^10.2.0",
Исправил

2022-02-28 07:38 UTC, merged